# Generated by Django 6.0.2 on 2026-02-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_tache_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
